### ISSUE TITLE
Missing dependency in CLIENT generationMode

### ISSUE THREAD

**Issue by mnembrini** [saw303/gradle-java-rest-api#228]
**Describe the bug**
When generating the client implementation, the dependency `implementation("io.micronaut:micronaut-validation")` is missing and needs to be added manually.
This is to use @Validated in the client class

**To Reproduce**
Create module with CLIENT generation. Import the client in another project and try to compile without adding additional dependencies

**Expected behavior**
Applying the plugin is enough to compile the project consuming the generated client

**Screenshots**

**Comment by saw303** [comment]
Version 2.3.14
